spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/surulere_local
spring.datasource.username=postgres
spring.datasource.password=beny_database_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
